// utils/newsStance.js
export const newsStanceMap = {
  '오마이뉴스': 'progressive',
  '한겨레': 'progressive',
  '프레시안': 'progressive',
  '경향신문': 'progressive',
  '딴지일보': 'progressive',
  '시사in': 'progressive',
  '미디어오늘': 'progressive',
  '노컷뉴스': 'progressive',
  '머니투데이': 'progressive',
  '이데일리': 'progressive',
  '레디앙': 'progressive',
  '미디어스': 'progressive',
  '민중의 소리': 'progressive',

  '조선일보': 'conservative',
  '중앙일보': 'conservative',
  '동아일보': 'conservative',
  '문화일보': 'conservative',
  '국민일보': 'conservative',
  '뉴데일리': 'conservative',
  '독립신문': 'conservative',
  '데일리안': 'conservative',
  '한국논단': 'conservative',
  '뉴스라이브': 'conservative',
  '아시아투데이': 'conservative',
  'cnb뉴스': 'conservative',
  '브레이크뉴스': 'conservative',
  '데일리NK': 'conservative',
  '쿠키뉴스': 'conservative',
  '연합뉴스': 'conservative',
  'YTN': 'conservative',

  '서울신문': 'neutral',
  '한국일보': 'neutral',
  '내일신문': 'neutral',
  '뉴시스': 'neutral',

  '한국경제': 'conservative',
  '매일경제': 'conservative',
  '서울경제': 'conservative',
  '헤럴드경제': 'conservative',
  '파이낸셜뉴스': 'neutral'
};
